Adição da página de criação e rotas
leonardosf98/diario-alimentar-app pull request #1
Opened 2023-11-09 14:45 UTC by leonardosf98

2023-11-09 15:21 UTC, LeonardoSSev requested changes

2023-11-09 15:21 UTC, LeonardoSSev commented on src/components/add-meal-button/add-meal-button.jsx
> +    // <button className="add-meal-button">Adicionar refeição</button>;
Pode apagar esse comentário. Uma boa prática é evitar comentários que não fazem sentido para o código

2023-11-09 15:21 UTC, LeonardoSSev commented on src/components/meal-list/meal-list.jsx
> +  const [meals, setMeals] = useState("Nenhuma refeição cadastrada");
Será que `meals` deveria receber uma string? Pois depois ele vai conter uma lista de refeições (cada refeição seria um objeto, não?)

2023-11-09 15:21 UTC, LeonardoSSev commented on src/components/modal/modal.jsx
> +function Modal({ onSubmit }) {
Sugiro trocar o nome desse componente para `"AddMealForm"` ou algo do tipo, dado que não estamos trabalhando com modal mais.

2023-11-09 15:21 UTC, LeonardoSSev commented on src/components/modal/modal.jsx
> +  const today = new Date().toJSON().slice(0, 10);
Qual seria o valor de `today` com esse slice?

2023-11-09 15:21 UTC, LeonardoSSev commented on src/components/modal/modal.jsx
> +  const today = new Date().toJSON().slice(0, 10);
Acho que o input de data não precisa ter os dados modificados antes pra que exiba certinho lá. O tratamento desse valor depois que o usuário muda o valor do campo deveria ser feito em outra função

2023-11-09 16:58 UTC, mechamobau requested changes

2023-11-09 16:58 UTC, mechamobau commented on src/components/add-meal-button/add-meal-button.jsx
> +    <Link to={"/createMeal"}>Adicionar refeição</Link>
```suggestion
    <Link to="/createMeal">Adicionar refeição</Link>
```

2023-11-09 16:58 UTC, mechamobau commented on src/components/meal-list/meal-list.jsx
> +  const [meals, setMeals] = useState("Nenhuma refeição cadastrada");
```suggestion
  const [meals, setMeals] = useState([]);
```

2023-11-09 16:58 UTC, mechamobau commented on src/components/modal/modal.jsx
> +  const today = new Date().toJSON().slice(0, 10);
Você tá cortando o horário, sendo que na especificação está pedindo para gravar o horário da refeição também

2023-11-09 16:58 UTC, mechamobau commented on src/components/modal/modal.jsx
> +  const [mealQuantity, setMealQuantity] = useState(12);
Por que esse estado começa como `12`?

2023-11-09 16:58 UTC, mechamobau commented on src/routes/root/root.jsx
> +    <div className="app">
Precisa dessa classe ainda?
```suggestion
function Root() {
  return (
    <div>
```

2023-11-09 16:58 UTC, mechamobau commented on src/routes/createMeal/createMeal.jsx
> +*/
Remove esse comentário
```suggestion
```

2023-11-09 18:26 UTC, leonardosf98 commented on src/components/modal/modal.jsx
> +  const today = new Date().toJSON().slice(0, 10);
Esse today serve para deixar uma data pronta, como se fosse um estado inicial! E no caso seria a data do dia atual

2023-12-13 15:34 UTC, LeonardoSSev approved these changes

2023-12-13 16:27 UTC, mechamobau commented on src/components/add-meal-button/add-meal-button.jsx
>  export default AddMealButton;
Por que esse componente existe?

2023-12-13 16:29 UTC, mechamobau commented on src/components/add-meal-form/add-meal-form.jsx
> +  const [mealItem, setMealItem] = useState([]);
Adiciona esse comentário aqui, depois vou te mostrar um jeito melhor
```suggestion
  // TODO: Refatorar os estados para centralizar em um objeto só
  const [mealName, setMealName] = useState("");
  const [mealDate, setMealDate] = useState(todayDate);
  const [mealTime, setMealTime] = useState(todayTime);
  const [mealItem, setMealItem] = useState([]);
```

2023-12-13 16:30 UTC, mechamobau commented on src/components/addMealItem/addMealItem.jsx
> +  const [mealQuantity, setMealQuantity] = useState();
Aqui também
```suggestion
  // TODO: Refatorar os estados para centralizar em um objeto só
  const [option, setOption] = useState("solid");
  const [measureUnit, setMeasureUnit] = useState("gramas");
  const [itemType, setItemType] = useState("");
  const [itemName, setItemName] = useState("Feijão");
  const [itemOptions, setItemOptions] = useState([
    "Feijão",
    "Ervilha",
    "Lentilha",
    "Grão de bico",
  ]);
  const [mealQuantity, setMealQuantity] = useState();
```

2023-12-13 16:32 UTC, mechamobau approved these changes
Muito bom, deixei algumas sugestões mas no todo tá tudo certo 🎉

2023-12-13 16:32 UTC, mechamobau commented on src/components/header/header.css
> +}
Usa uma classe, seletor de tag costuma dar problema de conflito
```suggestion
h1.title {
  background-color: blue;
}
```

2023-12-13 16:32 UTC, mechamobau commented on src/routes/root/root.jsx
> +    console.log(1);
Remove esse console
```suggestion
```

2023-12-19 21:51 UTC, leonardosf98 commented on src/components/addMealItem/addMealItem.jsx
> +  const [mealQuantity, setMealQuantity] = useState();
/* const [initial, setInitial] = {
    measureUnit: "gramas",
    itemType: "",
    itemName: "Feijão"
    itemOptions: ["Feijão","Ervilha","Lentilha","Grão de bico"],
    itemQuantity: undefined,
    error: false,
    foodTypes:["Leguminosas","Frutas","Cereais","Hortaliças"]
    };

    teria que então fazer o spread para manipular no useState? Ex: 
    const handleOptionChange = () => {
    if (initial.measureUnit === "gramas") {
      setState((initial) => {
        [...initial],measureUnit:"ml's"); essa linha se parece com o que fizemos no ID, porém o id foi uma propriedade criada, como nesse caso já existe a propriedade measureUnit ela será sobrescrita
   ...
    }
  };
    */

2023-12-20 20:31 UTC, merged